### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by 2805413893** [icon-lab/ResViT#1]
Hello, I don't understand very well how your dataset is placed. Can you describe in detail？I can see aligned dataset, unaligned dataset, and single dataset here. But in aligned datset,  are the data of different modalities placed in the same folder? such as t1 and t2 modalities, and whether the data format is in the form of jpg images.I hope you can describe the placement of the dataset images in detail, thank you

**Comment by onat-dalmaz** [comment]
Hello,
thanks for bringing this issue to our attention. As explained in the Read me file, the dataset should be structured in the following form:
/Datasets/BRATS/T2__FLAIR/
  ├── train
  ├── val  
  ├── test
Inside each folder, such as train, the source (left) and target (right) images lie side-by-side. For example:
![2474](https://user-images.githubusercontent.com/76726090/151752155-5a719ed8-4323-4b59-a743-970a4cee85c3.png)
whereas the data format is png.

I hope this explanation makes it more clear.

**Comment by 2805413893** [comment]
Thanks for your answer! It is very useful for me.
