### ISSUE TITLE
Plz explain on many to one case synthesis .How data should be organized

### ISSUE THREAD

**Issue by jamalgardezi** [icon-lab/ResViT#10]
can you please explain on multi-modal synthesis data organization?
How data should be arranged if T1,T2 ->Flair in Aligned data mode
In train folder there are two subfolders A & B . How Do we keep T1&T2 images all in folder A or in folder A &B. What about target images(Flairs)?
Secondly, you mentioned for multimodal to be in Green & red channel.. So do we need to convert them in green & red. 
Forexample : i have 2CT images at different time pts. i want to synthesize nd get target images as shown
Red T1
![valA0006](https://user-images.githubusercontent.com/19423485/170534527-884f75a6-434e-4d15-909a-4426bfc70f6b.jpg)
Green T2
![valA0017](https://user-images.githubusercontent.com/19423485/170534539-01c89531-f33c-48ad-a612-8fa824755644.jpg)
Target image 
![trainB0007](https://user-images.githubusercontent.com/19423485/170534608-2e7d1e45-8e6a-40e8-9e06-2b679b3655d1.jpg)
 or Stack Red&green  together in folder A nd targets in folder B
![Combined Stacks0015](https://user-images.githubusercontent.com/19423485/170535580-5402cfe8-f656-4d97-8348-c12cbc4c3753.jpg)

**Comment by onat-dalmaz** [comment]
Similar to the bottom-most figure, you need to stack input modality images within red and green channels on the left part. The target image should be in the red channel on the right part.
/Datasets/BRATS/T1_T2_FLAIR/
  ├── train
  ├── val  
  ├── test

if each image in the train, validation, and test folder follows the abovementioned convention, then it should work.
