### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by D-YL** [icon-lab/ResViT#11]
Excuse me,i have some problem in structuring my aligned dataset. the form of dataset BRATS are as follow, the item is not the same as you said "
   T1_T2
  ├── T2_FLAIR
  .
  .
  ├── T1_FLAIR_T2"
so how can i deal with it. 
plz~
![image](https://user-images.githubusercontent.com/62798090/174809549-82f820c0-e3e5-4a8d-8ebf-d17f71764344.png)

**Comment by onat-dalmaz** [comment]
First of all, you need to go through the .nii files and parse 3D volumes to extract 2D slices for modeling. For that, you can use python APIs developed for .nii file processing, such as, https://nipy.org/nibabel/gettingstarted.html
