### ISSUE TITLE
Download pre-trained ViT models from Google Problem

### ISSUE THREAD

**Issue by lewisj34** [icon-lab/ResViT#13]
The following command is wrong: 
`wget https://storage.googleapis.com/vit_models/imagenet21k/R50-ViT-B_16.npz`

Should be
`wget https://storage.googleapis.com/vit_models/imagenet21k/R50+ViT-B_16.npz`

**Comment by onat-dalmaz** [comment]
Hello,
Thanks for bringing up this issue. It is now corrected in README.md file.
