### ISSUE TITLE
Datasets used in this paper

### ISSUE THREAD

**Issue by ElegantLee** [icon-lab/ResViT#15]
Hello Mr. Dalmaz, thank you for your nice work. To better reproduce your experiment, could you provide the standard datasets that have been processed for use in the paper ？

**Comment by onat-dalmaz** [comment]
Please check out our full paper regarding details of the datasets used:
https://ieeexplore.ieee.org/document/9758823

**Comment by Le2Hu** [comment]
hello, i noticed that you have conducted experiments on 53 subjects from IXI, 55 subjects from BraTS. I want to learn more about how to choose the specific subjects from the original complete datasets. Is this related to that they contains data from multiple institutions or is this totally random? If it is possible, can u provide the filename lists corresponding to the original subjects? Thanks a lot.
