### ISSUE TITLE
53 subjects from IXI and 55 subjects from BraTS

### ISSUE THREAD

**Issue by Le2Hu** [icon-lab/ResViT#23]
hello, i noticed that you have conducted experiments on 53 subjects from IXI, 55 subjects from BraTS. I want to learn more about how to choose the specific subjects from the original complete datasets. Is this related to that they contains data from multiple institutions or is this totally random? If it is possible, can u provide the filename lists corresponding to the original subjects? Thanks a lot.

_Originally posted by @Le2Hu in https://github.com/icon-lab/ResViT/issues/15#issuecomment-2254139567_

**Comment by tcukur** [comment]
We actually selected the subjects sequentially starting from the beginning within the public datasets.
