### ISSUE TITLE
How to select data from the Brats dataset?

### ISSUE THREAD

**Issue by peanutbo** [icon-lab/ResViT#25]
Thanks for your excellent work.

I encountered some difficulties in searching for the dataset
I have found several papers on MRI synthesis that selected 55 samples from the Brats dataset. Is there a dedicated dataset for MRI synthesis? But I couldn't find this dataset. If not, how did you perform data filtering?

**Comment by tcukur** [comment]
Brats contains many more subjects, we just sample a subset sequentially, the specific version used was BraTS 2018.
