### ISSUE TITLE
Hello，I have a question

### ISSUE THREAD

**Issue by yeb1010** [icon-lab/ResViT#3]
Dear professor,
  Hello，I am a fresher of vit. When I run your code，I have some questions. For example, what's that mean and why this error? 
Mabe a stupid question from a student. --
<img width="961" alt="image" src="https://user-images.githubusercontent.com/100670728/156126396-52d50851-4fab-4f6f-8194-74c1130444c5.png">

**Comment by yeb1010** [comment]
After I delete the codes about down_samp and old=opt.old，it can run. I dont know why. Could you please tell me?

**Comment by onat-dalmaz** [comment]
Hi,
thanks for the inquiry, I also removed the lines old=opt.old and down_samp=opt.down_samp from resvit_one.py
They were unrelated arguments to the define_G function, they carry no importance.
thanks again,
Onat

**Comment by yeb1010** [comment]
Thanks for your answer!

**Comment by jamalgardezi** [comment]
> Thanks for your answer!

hi how to put data when you are using t1&t2 to get Flair in aligned data mode  for many to one case?

**Comment by D-YL** [comment]
您好，请问您是否复现成功了呢，可以请教下嘛

> Dear professor, Hello，I am a fresher of vit. When I run your code，I have some questions. For example, what's that mean and why this error? Mabe a stupid question from a student. -- <img alt="image" width="961" src="https://user-images.githubusercontent.com/100670728/156126396-52d50851-4fab-4f6f-8194-74c1130444c5.png">

**Comment by yeb1010** [comment]
> > Thanks for your answer!
> 
> hi how to put data when you are using t1&t2 to get Flair in aligned data mode for many to one case?

you can get answer from author‘s other reply of issue

**Comment by yeb1010** [comment]
> After I delete the codes about down_samp and old=opt.old，it can run

Like I said. After I delete the codes about down_samp and old=opt.old from resvit_one.py，it can run.
