### ISSUE TITLE
Hello,I have a question

### ISSUE THREAD

**Issue by yeb1010** [icon-lab/ResViT#4]
In the first issue of icon-lab/Resvit，you gave this image 
![image](https://user-images.githubusercontent.com/100670728/157402881-fcd19c73-73eb-4771-8f54-c326f266181d.png)
I know that the left is source and the right is target.  Could you please tell me which one is t1，t2 or flair ？

**Comment by yeb1010** [comment]
Hi，professor. For the many to one task,  could you please tell me that source and target image are still lying side by side?
For example, this?
![Brats18_CBICA_ALU_1_t1_t2_flair_98](https://user-images.githubusercontent.com/100670728/157997939-360f4699-aa6a-43bd-a354-9582a890fa8a.png)

**Comment by onat-dalmaz** [comment]
Hello,
For many-to-one tasks, the source modalities should be embedded in the channels of the source image. For example:
![2491](https://user-images.githubusercontent.com/76726090/158127260-916a6382-5611-4f0e-be0c-eae4d3453ab5.png)
In this one,  T1 and T2-weighted images are embedded into red and green channels of the source image, whereas the target FLAIR image is embedded into green channel of the target image.

**Comment by yeb1010** [comment]
thanks  a lot！
