### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by huaibovip** [icon-lab/ResViT#5]
I have a lot of questions about data preprocessing as shown below，
How to normalize brats and ixi image volume?
Are the intensity values of each volume normalized into a range [-1,1] ? (Max-Min Normalization)
Since the brats dataset contains images acquired under different clinical protocols and scanners, how the data normalization differs from IXI？

Could you share your python script for data preprocessing?
Thanks！

**Comment by onat-dalmaz** [comment]
Hello, you can access the script that contains data preprocessing steps from [data](https://github.com/icon-lab/ResViT/tree/main/data)/aligned_dataset.py [https://github.com/icon-lab/ResViT/blob/1963c1b449357307e371b4cc5796dbb6ee30dc5d/data/aligned_dataset.py](url)
