### ISSUE TITLE
hi professor，I have a question about data size

### ISSUE THREAD

**Issue by yeb1010** [icon-lab/ResViT#6]
As the picture shown，
![Uploading image.png…]()
#training images = 2086
#Validation images = 2086
In fact，my training images are not equal with Validation images.
Could you please tell me that whether the train data and validation data are same in your code？

**Comment by yeb1010** [comment]
<img width="266" alt="屏幕截图 2022-04-07 212710" src="https://user-images.githubusercontent.com/100670728/162209782-47fe9484-01ec-4623-b748-4ad2ac6180ed.png">

**Comment by yeb1010** [comment]
I also have a question about the details of dataset. In your paper，I know that there are 55 subjects. 
<img width="470" alt="屏幕截图 2022-04-08 133652" src="https://user-images.githubusercontent.com/100670728/162371816-8aa22b01-0781-428a-9663-1066671a20de.png">

In Readme file, 
<img width="430" alt="屏幕截图 2022-04-08 134107" src="https://user-images.githubusercontent.com/100670728/162371919-d3bb3aa9-6c64-41a4-ab84-5186a6bbae7d.png">

So you mean that in each folder ( like T1_T2 or T1_Flair....) there are 55 subjects? 25 subjects are reserved for training, 10 are reserved for validation, and 20 are reserved for testing?
Could you please tell me that whether each folder  concluded different motilities of same 55 subjects ？

**Comment by onat-dalmaz** [comment]
1.You probably have equal number of training and validation images.

2.Yes, each folder comprises different source-contrast pairs of modalities associated with the same 55 subjects.

**Comment by zzzzzj52** [comment]
Hi, I have the same question as u which is the number of training size equal  the number of validation size. Have u fix it ?

**Comment by zzzzzj52** [comment]
Hi, I have the same question as u which is the number of training size equal the number of validation size. Have u soloved it ?
