### ISSUE TITLE
A question about visdom in this code

### ISSUE THREAD

**Issue by yeb1010** [icon-lab/ResViT#7]
After I run the test code, the visdom tool generate nothing. But as the picture shown 
<img width="382" alt="屏幕截图 2022-04-08 111617" src="https://user-images.githubusercontent.com/100670728/162356087-a355346a-6dd5-4d40-94b4-bfa913b3951e.png">
<img width="1110" alt="屏幕截图 2022-04-08 111750" src="https://user-images.githubusercontent.com/100670728/162356153-3dde3360-c10e-4b91-af20-be034df45fa4.png">
![image](https://user-images.githubusercontent.com/100670728/162356184-6c56f867-4023-4b5a-bfe5-9c7bd546fc7c.png)
there is nothing code bug about visdom as the second picture shown.
BUT there is nothing in http://localhost:8097/, as the third picture shown.

**Comment by yeb1010** [comment]
I write some simple codes to test if my visdom tool or internet are wrong, but it generates the picture:

![image](https://user-images.githubusercontent.com/100670728/162356833-588e8590-b951-4d28-a83f-37ec6a93c384.png)

Could you please tell me why visdom in your code generate nothing?
thanks a lot!

**Comment by yeb1010** [comment]
I guess there are not codes to activate web visdom. But how do I assess my test data?

**Comment by onat-dalmaz** [comment]
Well, inference data is saved to the path specified by "results_dir". You can see your test data there.
