### ISSUE TITLE
Transformer_Discriminator

### ISSUE THREAD

**Issue by huaibovip** [icon-lab/ResViT#8]
https://github.com/icon-lab/ResViT/blob/1963c1b449357307e371b4cc5796dbb6ee30dc5d/models/networks.py#L167
Transformer_Discriminator is not implemented

**Comment by onat-dalmaz** [comment]
Hello, we did not implement a transformer-based discriminator for this study. Only the generator is considered a transformer. Hence, I removed those lines from networks.py script.
